### ISSUE TITLE
Cloning repo doesn't provide a way to accept the assignment

### ISSUE THREAD

**Issue by jkitchin** [markpatterson27/GitHub-Classroom-Introductory-Assignment#1]
If you just clone the repo you get this in Auto-Feedback

❌ Activity 1 - Accept assignment

Not sure how you got to this point without accepting the assignment. There is probably a bug in the marking code. Please submit an issue to
https://github.com/markpatterson27/GitHub-Classroom-Introductory-Assignment/issues.

Otherwise, very cool stuff happening here.

**Comment by markpatterson27** [comment]
The assignment is designed to be run via [GitHub Classroom](https://classroom.github.com). I'm not expecting anyone to try to run it by directly cloning the repo.

Instructions on setting up an assignment are in the [GH Docs](https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/create-an-individual-assignment). When you get to [Choosing a template repository](https://docs.github.com/en/education/manage-coursework-with-github-classroom/teach-with-github-classroom/create-an-individual-assignment#choosing-a-template-repository) you can use this repo as the template.

Thank you for the kind words.

**Comment by markpatterson27** [comment]
I've updated the feedback message to account for this use case.
7e2e3095713925d8d4832ac78abd035bcb68ca13
